/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { StrategyResponse } from './strategyResponse';

export type _CollectionModelStrategyEmbedded = {
  strategies?: StrategyResponse[];
};
