/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { _CollectionModelObjectEmbeddedObjectsItem } from './_collectionModelObjectEmbeddedObjectsItem';

export type _CollectionModelObjectEmbedded = {
  objects?: _CollectionModelObjectEmbeddedObjectsItem[];
};
