/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { EntityModelStrategy } from './entityModelStrategy';

export type _PagedModelEntityModelStrategyEmbedded = {
  strategies?: EntityModelStrategy[];
};
