/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { EntityModelTrade } from './entityModelTrade';

export type _PagedModelEntityModelTradeEmbedded = {
  trades?: EntityModelTrade[];
};
