/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type AccountCurrency = typeof AccountCurrency[keyof typeof AccountCurrency];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AccountCurrency = {
  EUR: 'EUR',
  USD: 'USD',
  JPY: 'JPY',
  GBP: 'GBP',
  AUD: 'AUD',
  NZD: 'NZD',
  CAD: 'CAD',
  CHF: 'CHF',
  HUF: 'HUF',
  MXN: 'MXN',
  ZAR: 'ZAR',
  CZK: 'CZK',
  PLN: 'PLN',
  TRY: 'TRY',
  RON: 'RON',
  CHN: 'CHN',
  SEK: 'SEK',
  DKK: 'DKK',
} as const;
