/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AccountRequestBodyCurrency } from './accountRequestBodyCurrency';

export interface AccountRequestBody {
  currency: AccountRequestBodyCurrency;
  id?: string;
  name: string;
  strategies: string[];
  trades: string[];
}
