/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { _CollectionModelStrategyEmbedded } from './_collectionModelStrategyEmbedded';
import type { Links } from './links';

export interface CollectionModelStrategy {
  _embedded?: _CollectionModelStrategyEmbedded;
  _links?: Links;
}
