/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { _CollectionModelEntityModelTradeEmbedded } from './_collectionModelEntityModelTradeEmbedded';
import type { Links } from './links';

export interface CollectionModelEntityModelTrade {
  _embedded?: _CollectionModelEntityModelTradeEmbedded;
  _links?: Links;
}
