/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { _CollectionModelObjectEmbedded } from './_collectionModelObjectEmbedded';
import type { Links } from './links';

export interface CollectionModelObject {
  _embedded?: _CollectionModelObjectEmbedded;
  _links?: Links;
}
