/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { _CollectionModelEntityModelStrategyEmbedded } from './_collectionModelEntityModelStrategyEmbedded';
import type { Links } from './links';

export interface CollectionModelEntityModelStrategy {
  _embedded?: _CollectionModelEntityModelStrategyEmbedded;
  _links?: Links;
}
