/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Links } from './links';

export interface EntityModelStrategy {
  _links?: Links;
  accountId: string;
  description?: string;
  name: string;
  subtype?: string;
}
