/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Strategy } from './strategy';
import type { EntityModelStrategy } from './entityModelStrategy';

export type GetItemResourceStrategyGet1200 = Strategy | EntityModelStrategy;
