/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Account } from './account';
import type { EntityModelAccount } from './entityModelAccount';

export type GetItemResourceAccountGet1200 = Account | EntityModelAccount;
