/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AbstractJsonSchemaPropertyObject } from './abstractJsonSchemaPropertyObject';

export type JsonSchemaProperties = {[key: string]: AbstractJsonSchemaPropertyObject};
