/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type NoteType = typeof NoteType[keyof typeof NoteType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NoteType = {
  IDEA: 'IDEA',
  IMPROVEMENT: 'IMPROVEMENT',
  OBSERVATION: 'OBSERVATION',
} as const;
