/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Note } from './note';
import type { TradeScreenshot } from './tradeScreenshot';
import type { OutcomeStatus } from './outcomeStatus';

export interface Outcome {
  isProfit: boolean;
  notes?: Note[];
  pnl: number;
  screenshot?: TradeScreenshot;
  status: OutcomeStatus;
}
