/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { _PagedModelEntityModelTradeScreenshotEmbedded } from './_pagedModelEntityModelTradeScreenshotEmbedded';
import type { Links } from './links';
import type { PageMetadata } from './pageMetadata';

export interface PagedModelEntityModelTradeScreenshot {
  _embedded?: _PagedModelEntityModelTradeScreenshotEmbedded;
  _links?: Links;
  page?: PageMetadata;
}
