/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { _PagedModelEntityModelTradeEmbedded } from './_pagedModelEntityModelTradeEmbedded';
import type { Links } from './links';
import type { PageMetadata } from './pageMetadata';

export interface PagedModelEntityModelTrade {
  _embedded?: _PagedModelEntityModelTradeEmbedded;
  _links?: Links;
  page?: PageMetadata;
}
