/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { _PagedModelEntityModelStrategyEmbedded } from './_pagedModelEntityModelStrategyEmbedded';
import type { Links } from './links';
import type { PageMetadata } from './pageMetadata';

export interface PagedModelEntityModelStrategy {
  _embedded?: _PagedModelEntityModelStrategyEmbedded;
  _links?: Links;
  page?: PageMetadata;
}
