/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface Strategy {
  accountId: string;
  description?: string;
  id?: string;
  name: string;
  subtype?: string;
}
