/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TickerMain } from './tickerMain';
import type { TickerSecondary } from './tickerSecondary';

export interface Ticker {
  main: TickerMain;
  secondary: TickerSecondary;
}
