/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type TradeDirection = typeof TradeDirection[keyof typeof TradeDirection];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TradeDirection = {
  LONG: 'LONG',
  SHORT: 'SHORT',
} as const;
