/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type TradeRequestBodyDirection = typeof TradeRequestBodyDirection[keyof typeof TradeRequestBodyDirection];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TradeRequestBodyDirection = {
  LONG: 'LONG',
  SHORT: 'SHORT',
} as const;
