/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Binary } from './binary';

export interface TradeScreenshotRequestBody {
  id?: string;
  image?: Binary;
  tradeId?: string;
}
