/**
 * Generated by orval v6.19.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type TradeResponseDirection = typeof TradeResponseDirection[keyof typeof TradeResponseDirection];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TradeResponseDirection = {
  LONG: 'LONG',
  SHORT: 'SHORT',
} as const;
